### ISSUE TITLE
ERROR [Vote] ❌ Received an error while trying to vote: 'processing response error'

### ISSUE THREAD

**Issue by fmu1337** [KYVENetwork/evm#4]
sup, I have issue with kyve, after few mins of working that error was appear: 

```
2021-11-01 12:05:42.955  INFO [Vote] 🗳  Voting "valid" on bundle IfsOrqVjE1MaokIzxHQqT0Uhk9_uiMIIlb6CIz-QLjs.
2021-11-01 12:05:47.928  ERROR [Vote] ❌ Received an error while trying to vote:
 Error  processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))\"},\"id\":232}\n", error={"stack":"Error: submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))\n    at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)\n    at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)\n    at /node_modules/@ethersproject/web/lib/index.js:241:46\n    at step (/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","message":"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))","code":-32603}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8ad820133843b9aca008301721594d1eae9cc4c0cc8d82c5800e2dae972a70f2c4d0d80b8449f2ce67821fb0eaea56313531aa24233c4742a4f452193dfee88c20895be82233f902e3b0000000000000000000000000000000000000000000000000000000000000001820a32a08a456570b50e6a159437cc002be955f5baf8a4ec9951f82734b0e1832aa34bf9a05231bce2f89655e987cf93d09ef3d36ed31d4b4bc6916542f9a3b3d7e086e5dd\"],\"id\":232,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://moonbeam-alpha.api.onfinality.io/public", code=SERVER_ERROR, version=web/5.5.0)
details:
{
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","error":{"code":-32603,"message":"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))"},"id":232}\n',
  error: Error: submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))
      at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
      at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)
      at /node_modules/@ethersproject/web/lib/index.js:241:46
      at step (/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: -32603,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0xf8ad820133843b9aca008301721594d1eae9cc4c0cc8d82c5800e2dae972a70f2c4d0d80b8449f2ce67821fb0eaea56313531aa24233c4742a4f452193dfee88c20895be82233f902e3b0000000000000000000000000000000000000000000000000000000000000001820a32a08a456570b50e6a159437cc002be955f5baf8a4ec9951f82734b0e1832aa34bf9a05231bce2f89655e987cf93d09ef3d36ed31d4b4bc6916542f9a3b3d7e086e5dd"],"id":232,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://moonbeam-alpha.api.onfinality.io/public',
  transaction: {
    nonce: 307,
    gasPrice: BigNumber {
      _hex: '0x3b9aca00',
      _isBigNumber: true
    },
    gasLimit: BigNumber {
      _hex: '0x017215',
      _isBigNumber: true
    },
    to: '0xd1EAe9CC4C0cC8D82c5800e2dAE972A70f2C4d0d',
    value: BigNumber {
      _hex: '0x00',
      _isBigNumber: true
    },
    data: '0x9f2ce67821fb0eaea56313531aa24233c4742a4f452193dfee88c20895be82233f902e3b0000000000000000000000000000000000000000000000000000000000000001',
    chainId: 1287,
    v: 2610,
    r: '0x8a456570b50e6a159437cc002be955f5baf8a4ec9951f82734b0e1832aa34bf9',
    s: '0x5231bce2f89655e987cf93d09ef3d36ed31d4b4bc6916542f9a3b3d7e086e5dd',
    from: '0x374F2318EEd399879Fc068Af1ce7a32cDbb61d0E',
    hash: '0xc19af0ae96be6286f4acc074c615ee6fb67349a19cdf6cce01c6a25f5b489068',
    type: null,
    confirmations: 0
  },
  transactionHash: '0xc19af0ae96be6286f4acc074c615ee6fb67349a19cdf6cce01c6a25f5b489068'
}
error stack:
• index.ts:225 Logger.makeError
    node_modules/@ethersproject/logger/src.ts/index.ts:225:28

• index.ts:237 Logger.throwError
    node_modules/@ethersproject/logger/src.ts/index.ts:237:20

• index.ts:284 <anonymous>
    node_modules/@ethersproject/web/src.ts/index.ts:284:28

• index.js:33 step
    node_modules/@ethersproject/web/lib/index.js:33:23

• index.js:14 <anonymous>
    node_modules/@ethersproject/web/lib/index.js:14:53

• index.js:5 fulfilled
    node_modules/@ethersproject/web/lib/index.js:5:58


```

OS: Ubuntu 20.04.3 LTS

**Comment by johnletey** [comment]
Hey @fmu1337, would you mind running your node with the `--endpoint https://rpc.testnet.moonbeam.network` flag. This is normally the fix for this error 😄

**Comment by fmu1337** [comment]
Thanks for fast reply.
Tryed with 

`docker create --name kyve-evm-node --restart=always kyve/evm:latest --pool $KYVE_POOL_ADDRESS --private-key $KYVE_PRIVATE_KEY --stake $STAKE  --endpoint "https://rpc.testnet.moonbeam.network"`

but same error:

```
2021-11-01 13:55:39.158  INFO [Vote] 🗳  Voting "valid" on bundle gzDDM2pSi78Y5YobpzCThPHFQC7EvrpInITd0BDCvlI.
2021-11-01 13:55:45.192  ERROR [Vote] ❌ Received an error while trying to vote:
 Error  processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))\"},\"id\":168}\n", error={"stack":"Error: submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))\n    at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)\n    at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)\n    at /node_modules/@ethersproject/web/lib/index.js:241:46\n    at step (/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","message":"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))","code":-32603}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8ad820133843b9aca008301721594d1eae9cc4c0cc8d82c5800e2dae972a70f2c4d0d80b8449f2ce6788330c3336a528bbf18e58a1ba7309384f1c5402ec4beba489c84ddd010c2be520000000000000000000000000000000000000000000000000000000000000001820a32a0ceaee6025ea216f2ad54549949faa1a10759b59bc19a3fc307e9e3e998eaa008a04e613b24f9cf800cc5a066c47ada29b8b6efa16c498c9b427ba684d2d54f6218\"],\"id\":168,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.testnet.moonbeam.network", code=SERVER_ERROR, version=web/5.5.0)
details:
{
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","error":{"code":-32603,"message":"submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))"},"id":168}\n',
  error: Error: submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Payment))
      at getResult (/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:142:21)
      at processJsonFunc (/node_modules/@ethersproject/web/lib/index.js:309:22)
      at /node_modules/@ethersproject/web/lib/index.js:241:46
      at step (/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: -32603,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0xf8ad820133843b9aca008301721594d1eae9cc4c0cc8d82c5800e2dae972a70f2c4d0d80b8449f2ce6788330c3336a528bbf18e58a1ba7309384f1c5402ec4beba489c84ddd010c2be520000000000000000000000000000000000000000000000000000000000000001820a32a0ceaee6025ea216f2ad54549949faa1a10759b59bc19a3fc307e9e3e998eaa008a04e613b24f9cf800cc5a066c47ada29b8b6efa16c498c9b427ba684d2d54f6218"],"id":168,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://rpc.testnet.moonbeam.network',
  transaction: {
    nonce: 307,
    gasPrice: BigNumber {
      _hex: '0x3b9aca00',
      _isBigNumber: true
    },
    gasLimit: BigNumber {
      _hex: '0x017215',
      _isBigNumber: true
    },
    to: '0xd1EAe9CC4C0cC8D82c5800e2dAE972A70f2C4d0d',
    value: BigNumber {
      _hex: '0x00',
      _isBigNumber: true
    },
    data: '0x9f2ce6788330c3336a528bbf18e58a1ba7309384f1c5402ec4beba489c84ddd010c2be520000000000000000000000000000000000000000000000000000000000000001',
    chainId: 1287,
    v: 2610,
    r: '0xceaee6025ea216f2ad54549949faa1a10759b59bc19a3fc307e9e3e998eaa008',
    s: '0x4e613b24f9cf800cc5a066c47ada29b8b6efa16c498c9b427ba684d2d54f6218',
    from: '0x374F2318EEd399879Fc068Af1ce7a32cDbb61d0E',
    hash: '0xcd64dabfafb2ed05c1d153c00735be11ca9627975044b6439c335333a5285235',
    type: null,
    confirmations: 0
  },
  transactionHash: '0xcd64dabfafb2ed05c1d153c00735be11ca9627975044b6439c335333a5285235'
}
error stack:
• index.ts:225 Logger.makeError
    node_modules/@ethersproject/logger/src.ts/index.ts:225:28

• index.ts:237 Logger.throwError
    node_modules/@ethersproject/logger/src.ts/index.ts:237:20

• index.ts:284 <anonymous>
    node_modules/@ethersproject/web/src.ts/index.ts:284:28

• index.js:33 step
    node_modules/@ethersproject/web/lib/index.js:33:23

• index.js:14 <anonymous>
    node_modules/@ethersproject/web/lib/index.js:14:53

• index.js:5 fulfilled

```

**Comment by johnletey** [comment]
Hmmm okay that's strange, by any chance do you have any $DEV tokens (the native token of Moonbase Alpha)?

Or just $KYVE tokens?

**Comment by fmu1337** [comment]
> Hmmm okay that's strange, by any chance do you have any $DEV tokens (the native token of Moonbase Alpha)?
> 
> Or just $KYVE tokens?


https://moonbase-blockscout.testnet.moonbeam.network/address/0x374F2318EEd399879Fc068Af1ce7a32cDbb61d0E/transactions

0.000075018 DEV
And 900 $KYVE tokens

**Comment by johnletey** [comment]
Yeah that's not enough $DEV tokens 😄

I've gone ahead and sent you 0.01 DEV to that address.
Mind trying it again?

https://moonbase.moonscan.io/tx/0xf8967aee6626dd74019cea4a06a548e367ff7e0f3c0cb406cebe1ebaafb3da37

**Comment by fmu1337** [comment]
Yep, all was working, thanks!
And last questions - where I can get $DEV tokens?

**Comment by johnletey** [comment]
Glad it's all working, going to go ahead and close this then!

You can get $DEV tokens from the Discord faucet that Moonbeam offers.

https://docs.moonbeam.network/builders/get-started/moonbase/#discord-mission-control
